rabbitmq:
  uri: "amqp://guest:guest@localhost:5672/"

options:
  spy: true
  automessage: true
  sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
  #sound: "ORB_PICKUP" #1.7


channels:
  global:
    format: "[GLOBAL] {prefix}{display_name} : &f{message}"
    alias: "g"
    url_mode: 1 # check https://github.com/Mineaurion/Aurionchat/#url-mode for reference
  infinity:
    format: "[&6I&f] {prefix}{display_name} : &f{message}"
    alias: "inf"
    url_mode: 1 # check https://github.com/Mineaurion/Aurionchat/#url-mode for reference
  revelation:
    format: "[&5R&f] {prefix}{display_name} : &f{message}"
    alias: "reve"
    url_mode: 1 # check https://github.com/Mineaurion/Aurionchat/#url-mode for reference